#!/usr/bin/env python
"""Assemble submission Figure 1 from versioned source panels.

The analysis scripts write source panels to ``figures/source``. This script
only lays out Figure 1; it does not refit models or recalculate statistics.
Figures 2, 3, and 7 are generated by ``make_reviewed_figures.py``; Figure 4 by
``make_figure4.py``; Figure 5 by ``analysis/spatial_contextualization.py``; and
Figure 6 by ``make_virtual_knockout_figure.R``. Keeping
one canonical producer per final figure prevents stale layouts from
overwriting reviewed submission files.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "figures" / "source"
FINAL = ROOT / "figures" / "final"
FINAL.mkdir(parents=True, exist_ok=True)

plt.rcParams.update(
    {"font.family": "DejaVu Sans", "font.size": 9, "figure.dpi": 150}
)


def source(name: str) -> Path:
    path = SOURCE / name
    if not path.exists():
        raise FileNotFoundError(
            f"Missing source panel {path}. Run workflow/run_core_analysis.ps1 first."
        )
    return path


def panel_label(ax, letter: str) -> None:
    ax.text(
        -0.018,
        1.025,
        letter,
        transform=ax.transAxes,
        fontsize=16,
        fontweight="bold",
        va="bottom",
        ha="right",
    )


def add_panel(ax, filename: str, letter: str, title: str, crop_top: float = 1.0) -> None:
    image = mpimg.imread(source(filename))
    if crop_top < 1.0:
        image = image[: int(image.shape[0] * crop_top), :]
    ax.imshow(image)
    ax.axis("off")
    panel_label(ax, letter)
    ax.set_title(title, fontsize=9, loc="left", pad=5)


def save_both(fig, stem: str) -> None:
    fig.savefig(FINAL / f"{stem}.png", dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(FINAL / f"{stem}.pdf", bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("saved", stem)


def grid_figure(items, nrows: int, ncols: int, stem: str, figsize) -> None:
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize)
    axes = np.atleast_1d(axes).ravel()
    for ax in axes:
        ax.axis("off")
    for ax, item in zip(axes, items):
        add_panel(ax, *item)
    fig.tight_layout(pad=1.1)
    save_both(fig, stem)


grid_figure(
    [
        ("umap_clusters.png", "A", "Leiden clusters"),
        ("umap_celltype.png", "B", "Marker-panel cell-type labels"),
        ("umap_group.png", "C", "Clinical/source groups"),
        ("umap_dataset.png", "D", "Source datasets (descriptive visualization)"),
        ("fig1e_v4_ec_fraction.png", "E", "EC fraction by sampling unit"),
        ("fig1f_v4_retained_cells.png", "F", "Retained cells per library"),
    ],
    2,
    3,
    "Figure1",
    (16, 9.5),
)
